version: '3.8'

services:
  backend:
    build: ./backend
    container_name: learning-platform-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - FLASK_ENV=production
      - COHERE_API_KEY=${COHERE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/profile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: learning-platform-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000

networks:
  default:
    name: learning-platform-network

volumes:
  backend_data:
    driver: local